POST http://localhost:3000/api/user HTTP/1.1
Content-Type: application/json

{
   "firstName": "Jack",
   "lastName": "Michel",
   "email": "jack@gmail.com",
   "password": "qwerty",
   "birthday": "1980-08-08",
   "gender": "male"
}